version: "2.1"
services:
  jobmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  influxdb:
    image: influxdb:latest
    restart: always
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      INFLUXDB_DB: flink
      INFLUXDB_ADMIN_USER: flink-metrics
      INFLUXDB_ADMIN_PASSWORD: qwerty
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
